### ISSUE TITLE
Clarify install

### ISSUE THREAD

**Issue by villanus** [papandreou/node-inkscape#4]
What does it mean to have inkscape binary in your path?    Trying to get this to work on windows.

**Comment by villanus** [comment]
Make sure you have node.js and npm installed, and that the inkscape binary is in your PATH, then run:

**Comment by papandreou** [comment]
It means that the path where the `inkscape` binary is installed has to be included in the `$PATH` environment variable on your system. See https://www.computerhope.com/issues/ch000549.htm

If that doesn't work for you, we can add the option to specify the absolute path to the `inkscape` binary when instantiating the `Inkscape` object.

**Comment by villanus** [comment]
Thank You.
Sorry about confusion
