### ISSUE TITLE
Exports as PNG with '--export-plain-svg'

### ISSUE THREAD

**Issue by SnooHD** [papandreou/node-inkscape#5]
I am trying to make adjustments to an SVG file through Inkscape, and then i want the changed SVG to be returned. But i am always getting a PNG as output.

```
let buffer = new Future();
const Writable = require('stream').Writable;
const resultStream = new Writable;
resultStream._write = function(n){};
ink = new Inkscape(['--verb=EditSelectAll --verb=ObjectToPath --export-plain-svg']);

const chunks = [];
ink.on("data", function(chunk){
  chunks.push(chunk);
});

ink.on("end", function(){
  buffer.return(Buffer.concat(chunks));
});

ink.pipe(resultStream);
ink.end(svg);

return buffer.wait(); //returns a png
```

Is there something i am doing wrong?
Thanks!

**Comment by papandreou** [comment]
The array passed to the constructor needs to have the command line arguments separated. This should work:

```js
ink = new Inkscape(['--verb=EditSelectAll', '--verb=ObjectToPath', '--export-plain-svg']);
```

Since [there's even a test for it](https://github.com/papandreou/node-inkscape/blob/0407d6b640b5c77e84062befc8356ace8a7b5a4a/test/Inkscape.js#L31-L34) I'm fairly certain it'll work :)

**Comment by SnooHD** [comment]
A yes, well it makes sense that an array constructor needs an array :laughing: 
Thank you! Its working now :)
