### ISSUE TITLE
Using verbs with Inkscape CLI. Having trouble. Any advice?

### ISSUE THREAD

**Issue by drewrwilson** [papandreou/node-inkscape#6]
Hi! I like your npm package! I'm trying to use it to do some union operations. If I'm running the commands directly from the command line, I'd use this command: `inkscape -f temp.svg --verb=EditDeselect --select=shapeA --select=shapeB --verb=SelectionUnion --verb=FileSave --verb=FileClose` 

I can't get this to work! Do verbs work as parameters using your module? Any thoughts or advice?

**Comment by papandreou** [comment]
Hi, thanks! Does this work?

```js
const Inkscape = require('inkscape');
const inkscape = new Inkscape([
  '--verb=EditDeselect',
  '--select=shapeA',
  '--select=shapeB',
  '--verb=SelectionUnion',
  '--verb=FileSave',
  '--verb=FileClose'
]);
readableStream.pipe(inkscape).pipe(writableStream); // ...
```

**Comment by drewrwilson** [comment]
Thanks for the reply!

That didn't work for me. the code that I have is:

```const Inkscape = require('inkscape');
fs = require('fs');
const inkscape = new Inkscape([
  '--verb=EditDeselect',
  '--select=lasertext',
  '--select=bar',
  '--verb=SelectionUnion',
  '--verb=FileSave',
  '--verb=FileClose',
  '--verb=FileQuit'
]);

var readableStream = fs.createReadStream('./temp.svg');
var writableStream = fs.createWriteStream('./output.svg');

readableStream.pipe(inkscape).pipe(writableStream);

```
Is that correct? 

This is the output that I get

```internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: inkscape --without-gui --verb=EditDeselect --select=lasertext --select=bar --verb=SelectionUnion --verb=FileSave --verb=FileClose --verb=FileQuit -e=/var/folders/1l/1hvk0_05731b9wx02p7jxrr00000gn/T/117103-50331-10l4x1e.7axx.png /var/folders/1l/1hvk0_05731b9wx02p7jxrr00000gn/T/117103-50331-1xnfqzv.8wqr.svg did not write an output file.
STDOUT: 
STDERR: WARNING: ignoring verb EditDeselect - GUI required for this verb.

** (inkscape-bin:50332): CRITICAL **: static void Inkscape::EditVerb::perform(SPAction *, void *): assertion 'ensure_desktop_valid(action)' failed
WARNING: ignoring verb FileSave - GUI required for this verb.

** (inkscape-bin:50332): CRITICAL **: static void Inkscape::FileVerb::perform(SPAction *, void *): assertion 'ensure_desktop_valid(action)' failed
WARNING: ignoring verb FileClose - GUI required for this verb.

** (inkscape-bin:50332): CRITICAL **: static void Inkscape::FileVerb::perform(SPAction *, void *): assertion 'ensure_desktop_valid(action)' failed

Emergency save activated!
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at www.inkscape.org
with a detailed description of the steps leading to the crash, so we can fix it.
** Message: Error: Inkscape encountered an internal error and will close now.


    at Inkscape.<anonymous> (/Users/me/testing-node-inkscape/node_modules/inkscape/lib/Inkscape.js:174:40)
    at FSReqWrap.oncomplete (fs.js:154:21)```


A couple things:  I think the `this.inkscapeArgs = ['--without-gui'];` on line 19 of inkscape.js is causing a problem. I replaced it with `this.inkscapeArgs = ['--without-gui'];` which got me a little further--it launches inkscape but then fails and give this output:

```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: inkscape --verb=EditDeselect --select=lasertext --select=bar --verb=SelectionUnion --verb=FileSave --verb=FileClose --verb=FileQuit -e=/var/folders/1l/1hvk0_05731b9wx02p7jxrr00000gn/T/117103-50455-1c924z8.1u4lh.png /var/folders/1l/1hvk0_05731b9wx02p7jxrr00000gn/T/117103-50455-1xvb1fw.06px.svg did not write an output file.
STDOUT: 
STDERR: 
    at Inkscape.<anonymous> (/Users/me/testing-node-inkscape/node_modules/inkscape/lib/Inkscape.js:174:40)
    at FSReqWrap.oncomplete (fs.js:154:21)
```

**Comment by papandreou** [comment]
Ah, that helps. Then it’s due to the fact that this module [hardcodes the `—without-gui` switch](https://github.com/papandreou/node-inkscape/blob/master/lib/Inkscape.js#L19) when invoking the inkscape cli. IIRC that prevents the inkscape app from opening a window that’s just left open.

Does it work if you temporarily patch it not to add `—without-gui`? If it does, we can look into how we could get this use case supported.

**Comment by drewrwilson** [comment]
Yeah, I think that's part of it. I removed that line that hardcodes the `without-gui` switch. That's a step forward, but it still isn't working for me. 

This is my script:

```
const Inkscape = require('inkscape');
fs = require('fs');
const inkscape = new Inkscape([
  '--verb=EditDeselect',
  '--select=lasertext',
  '--select=bar',
  '--verb=SelectionUnion',
  '--verb=FileSave',
  '--verb=FileClose',
  '--verb=FileQuit'
]);

var readableStream = fs.createReadStream('./temp.svg');
var writableStream = fs.createWriteStream('./out.svg');

readableStream.pipe(inkscape).pipe(writableStream);
```

And when I run it by typing: `node index.js`  I get this output:

```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: inkscape --verb=EditDeselect --select=lasertext --select=bar --verb=SelectionUnion --verb=FileSave --verb=FileClose --verb=FileQuit -e=/var/folders/1l/1hvk0_05731b9wx02p7jxrr00000gn/T/117104-55306-1sadmtn.b1axk.png /var/folders/1l/1hvk0_05731b9wx02p7jxrr00000gn/T/117104-55306-1t60shg.y6sa.svg did not write an output file.
STDOUT: 
STDERR: 
    at Inkscape.<anonymous> (/Users/me/testing-node-inkscape/node_modules/inkscape/lib/Inkscape.js:174:40)
    at FSReqWrap.oncomplete (fs.js:154:21)

```

**Comment by papandreou** [comment]
Try with 1.2.0 now. When `--verb=...` is used, it'll omit `--without-gui` and assume that the input file will be overwritten with the desired output via `--verb=FileSave`.

**Comment by drewrwilson** [comment]
Cool! You're awesome! :) I'll test it right now and let you know how it goes

**Comment by drewrwilson** [comment]
Worked great for me! You rule! Thanks for all your help and for updating your module :) :)

**Comment by Cybernetic1** [comment]
You may try this:

`inkscape --batch-process --actions="select-all:all;FitCanvasToSelection;FileSave;FileClose;"  you-file.svg`

I am using Inkscape 1.0.2.
